# Copyright 2019-2021 Tauri Programme within The Commons Conservancy
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

name: updater test artifacts
on:
  tags: [ v* ]

jobs:
  build-artifacts:
    runs-on: ${{ matrix.platform }}

    strategy:
      fail-fast: false
      matrix:
        platform: [ ubuntu-latest, macos-latest, windows-latest ]

    steps:
      - uses: actions/checkout@v3
      - name: install stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: install webkit2gtk (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.0
      - name: build sample artifacts (updater)
        working-directory: ./src-tauri
        run: |
          npm install
          node ../../tooling/cli.js/bin/tauri build
        env:
          TAURI_PRIVATE_KEY: ${{secret.TAURI_PRIVATE_KEY}}
          TAURI_KEY_PASSWORD: ${{secret.TAURI_KEY_PASSWORD}}

      - uses: actions/upload-artifact@v2
        if: matrix.platform == 'ubuntu-latest'
        with:
          name: linux-updater-artifacts
          path: ./target/release/bundle/appimage/updater-example_*.AppImage.*

      - uses: actions/upload-artifact@v2
        if: matrix.platform == 'windows-latest'
        with:
          name: windows-updater-artifacts
          path: ./target/release/bundle/msi/*

      - uses: actions/upload-artifact@v2
        if: matrix.platform == 'macos-latest'
        with:
          name: macos-updater-artifacts
          path: ./target/release/bundle/macos/updater-example_*.app.tar.*
